#!/bin/bash
# Deploy / update the rokid-shim on an LXC that already runs mcp-servers.
#
# Idempotent: re-running is safe.
#   - If /opt/aiglasses exists -> git pull
#   - If .env exists           -> leaves it alone (no clobber)
#   - Always rebuilds the image and `up -d` (Docker no-ops if nothing changed)
#
# Usage (run on the LXC as root):
#   curl -fsSL https://raw.githubusercontent.com/chrohrbach/aiglasses/main/deploy.sh | bash -s -- <ROKID_AK>
# OR if already cloned:
#   cd /opt/aiglasses && ROKID_AK=<ak> ./deploy.sh
#
# Requires on the LXC: git, docker compose, an existing mcp-servers/
# checkout at /opt/mcp-servers, the `mcp-network` Docker network up.

set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/chrohrbach/aiglasses.git}"
TARGET_DIR="${TARGET_DIR:-/opt/aiglasses}"
MCP_SERVERS_DIR="${MCP_SERVERS_DIR:-/opt/mcp-servers}"
SITES_DIR="${MCP_SERVERS_DIR}/deploy-local/local-caddy/sites"

# ---------------------------------------------------------------------------
# 0. Resolve ROKID_AK (first arg wins, else env, else fail)
# ---------------------------------------------------------------------------
ROKID_AK="${1:-${ROKID_AK:-}}"
if [[ -z "$ROKID_AK" ]]; then
  echo "ERROR: pass ROKID_AK as the first arg or env var." >&2
  echo "       Generate one with: openssl rand -hex 24" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# 1. Pre-flight
# ---------------------------------------------------------------------------
echo "==> Pre-flight"
command -v git >/dev/null || { echo "git missing" >&2; exit 1; }
command -v docker >/dev/null || { echo "docker missing" >&2; exit 1; }
docker network inspect mcp-network >/dev/null 2>&1 \
  || { echo "ERROR: docker network 'mcp-network' is not up. Bring mcp-servers up first." >&2; exit 1; }
[[ -d "$MCP_SERVERS_DIR" ]] \
  || { echo "ERROR: $MCP_SERVERS_DIR not found." >&2; exit 1; }
[[ -d "$SITES_DIR" ]] || mkdir -p "$SITES_DIR"

# ---------------------------------------------------------------------------
# 2. Clone or update the repo
# ---------------------------------------------------------------------------
echo "==> Repo sync"
if [[ -d "$TARGET_DIR/.git" ]]; then
  echo "  $TARGET_DIR exists, pulling..."
  git -C "$TARGET_DIR" fetch --quiet origin main
  git -C "$TARGET_DIR" reset --hard origin/main
else
  echo "  cloning into $TARGET_DIR..."
  git clone --quiet "$REPO_URL" "$TARGET_DIR"
fi
cd "$TARGET_DIR"

# ---------------------------------------------------------------------------
# 3. Bootstrap .env (preserve existing)
# ---------------------------------------------------------------------------
echo "==> Env"
if [[ -f .env ]]; then
  echo "  .env exists — leaving it alone."
  if ! grep -q "^ROKID_AK=" .env; then
    echo "ROKID_AK=$ROKID_AK" >> .env
    echo "  added ROKID_AK to existing .env"
  fi
else
  cat > .env <<EOF
# Generated by deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Edit freely; this file is gitignored.
ROKID_AK=$ROKID_AK

# Defaults from .env.example are all picked up by docker-compose
# via \${VAR:-default} substitution. Override here as needed.
#
# Examples:
# ROKID_MCP_PROFILES=mail,personal,knowledge
# ROKID_FULL_MODEL=claude-haiku-4-5
# PUSH_SHARED_SECRET=$(openssl rand -hex 16)
# ROKID_CALLBACK_URL=https://api.rokid.com/metis/callback/message  # confirm host on Lingzhu
# ROKID_SK_TOKEN=                                                  # from https://account-web.rokid.com/token
EOF
  chmod 600 .env
  echo "  created $TARGET_DIR/.env (mode 600)"
fi

# ---------------------------------------------------------------------------
# 4. Drop the Caddy snippet (only if absent/different)
# ---------------------------------------------------------------------------
echo "==> Caddy snippet"
CADDY_SRC="$TARGET_DIR/deploy/glasses_hostname.caddyfile"
CADDY_DST="$SITES_DIR/glasses_hostname.caddyfile"
if ! cmp -s "$CADDY_SRC" "$CADDY_DST" 2>/dev/null; then
  cp "$CADDY_SRC" "$CADDY_DST"
  echo "  copied $CADDY_SRC -> $CADDY_DST"
  if docker ps --format '{{.Names}}' | grep -q '^caddy$'; then
    docker restart caddy >/dev/null
    echo "  caddy restarted"
  else
    echo "  WARN: no caddy container running — apply config manually"
  fi
else
  echo "  caddy snippet already up-to-date"
fi

# ---------------------------------------------------------------------------
# 5. Build + start the container
# ---------------------------------------------------------------------------
echo "==> Container"
docker compose --env-file .env up -d --build
docker compose --env-file .env ps

# ---------------------------------------------------------------------------
# 6. Smoke test
# ---------------------------------------------------------------------------
echo "==> Smoke test"
sleep 3
# In-cluster — should be 200 with mcp_tool_count > 0
curl -fsS http://localhost:8024/health \
  && echo \
  || { echo "ERROR: in-cluster /health failed"; exit 1; }

# Public (only works once Cloudflare Tunnel route glasses.rohrbach.app → :80 is up)
echo "  testing public glasses.rohrbach.app/health (404/200 both OK if tunnel routes elsewhere)..."
curl -sS -m 5 -o /dev/null -w "  glasses.rohrbach.app/health -> HTTP %{http_code}\n" \
  https://glasses.rohrbach.app/health 2>&1 || true

echo
echo "==> Done. Next steps:"
echo "  1. (one-time) Add a Cloudflare Tunnel route: glasses.rohrbach.app -> http://<lxc-ip>:80"
echo "  2. Create the custom agent on https://rizon.rokid.com/"
echo "     - SSE endpoint: https://glasses.rohrbach.app/rokid/agent"
echo "     - Auth AK:      <the ROKID_AK from $TARGET_DIR/.env>"
echo "  3. Test from the glasses."
